- lib/ui/views/groups/add_assignment_view.dart
- lib/ui/views/groups/edit_group_view.dart
- lib/ui/views/groups/new_group_view.dart
- lib/ui/views/groups/update_assignment_view.dart
- lib/ui/views/profile/edit_profile_view.dart
- lib/ui/views/projects/edit_project_view.dart
Fixes #13 
The buttons were not properly stretched in edit & create views because of a column's missing property i.e `              crossAxisAlignment: CrossAxisAlignment.stretch`. 
Added the above property to edit & create views.
> Minor UI fixes in Edit & Create Views

- lib/ui/views/about/about_tos_view.dart
- lib/ui/views/about/about_view.dart
- lib/utils/router.dart
- test/ui_tests/about/about_tos_view_test.dart
- test/ui_tests/about/about_view_test.dart
In this Pull Request, I have implemented [Terms of Service](https://circuitverse.org/tos) instead of using WebView to load the page from URL.
Terms of Service "content" is untouched and straight away used from [Terms of Service](https://circuitverse.org/tos) Page. Links like website URL is retained and will open on the default Android/iOS selected browser (or will ask confirmation if no default browser is set).
Also Fixes #21 , Fixes #18
> About CV: Bringup Terms of Service Page.

- test/setup/test_helpers.dart
- test/ui_tests/groups/my_groups_view_test.dart
In this Pull Request I have written UI Test for My Groups View.
This UI Test does a complete end-to-end Test for this view which includes -
- Testing Groups cards for both mentored and member.
- Testing the Group Details like title and members are visible.
- Testing the Buttons like View, Delete and Edit are pushed to their right routes.
We had to mock `MyGroupsViewModel`, `GroupDetailsViewModel` for GroupDetails view, `LocalStorage` for mocking User Details, `DialogService` since it calls native platform dialog service which is not possible to test.
> Bringup UI Test for My Groups View

- test/ui_tests/profile/edit_profile_view_test.dart
Fixes the failure of UI Tests in mainline master branch caused due to merging #42 and #43 together. #43 switched Country and Institute Field to `CVTypeAheadField` due to which the tests failed.
> UI Test: EditProfileView: Fix Test Caused due to #42 + #43

- lib/ui/views/ib/ib_page_view.dart
- pubspec.lock
Fixes #113
- Custom Image Builder that supports SVG and falls back to default for other types of images.
> fix(ib): Add SVG Support to images.

- lib/models/ib/ib_pop_quiz_question.dart
- lib/services/ib_engine_service.dart
- lib/ui/views/ib/builders/ib_interaction_builder.dart
- lib/ui/views/ib/builders/ib_pop_quiz_builder.dart
- lib/ui/views/ib/builders/ib_webview_builder.dart
- lib/ui/views/ib/components/ib_pop_quiz.dart
- lib/ui/views/ib/components/ib_pop_quiz_button.dart
- lib/ui/views/ib/ib_page_view.dart
- lib/ui/views/ib/syntaxes/ib_md_tag_syntax.dart
- lib/viewmodels/ib/ib_page_viewmodel.dart
- test/service_tests/ib_engine_test.dart
- test/viewmodel_tests/ib/ib_page_viewmodel_test.dart
Adds Support for Pop Quizzes using custom Markdown Builder and using `{:quiz}` markdown syntax. 
1. Allow consuming raw markdown pop quiz content from `IbMdSyntax`.
2. Develop Pop Quiz Builder and it's UI components to build Pop Quiz Questions.
3. Add parsing pop quiz logic in Ib Engine Service and correspondingly to Ib Page View Model to fetch pop quiz questions.
> feat(ib): Add support for Pop Quizzes.

- .githooks/commit-msg
- README.md
- commitlint.config.js
- Added git's `commit-msg` hook in `.githooks/commit-msg`.
- To use our custom githooks directory, we need to run `git config core.hooksPath .githooks/`.
- `commitlint` should be installed globally to be able to run linting.
- Added commit linting setup step in README.md
> feat(commitlint): enforce commit linting via git hooks

- lib/ui/views/ib/builders/ib_mathjax_builder.dart
- lib/ui/views/ib/builders/ib_subscript_builder.dart
- lib/ui/views/ib/builders/ib_superscript_builder.dart
- lib/ui/views/ib/ib_page_view.dart
- lib/ui/views/ib/syntaxes/ib_embed_syntax.dart
- lib/ui/views/ib/syntaxes/ib_liquid_syntax.dart
1. Mathjax: Since custom and auto tagging is not supported, we remove those keywords to allow rendering the basic formula without the required feature.
2. Subscript and Superscript Builder: Add support for non-selectable text.
3. Embed Syntax: Enhance RegEx for iframe capturing which now supports multi-line iframe tag.
4. Liquid Syntax: Enhance RegEx to support single quotes (') as well.
**Note: Please don't squash and merge**
> fix(ib): bug fixes and misc improvements 

- lib/ui/views/ib/ib_page_view.dart
> fix(ib): scroll to local links within page

- lib/ui/views/authentication/components/auth_options_view.dart
- lib/ui/views/cv_landing_view.dart
- pubspec.lock
- pubspec.yaml
Icon designs remain same except fill/outline effects.
Fixes #119
Screenshots of the changes -
From -> To
> fix(119): swap `flutter_icons` with `fluttericon`

- .github/workflows/cd.yml
- android/fastlane/Fastfile
- Uses GitHub releases & associated tags to ship the app to play store.
- gh-actions accepts 'vx.y.z-beta' for beta builds and 'vx.y.z' for prod builds.
> feat(cd): enable deployments via GitHub releases

- CONTRIBUTING.md
Fixes #139 
Derived from [CircuitVerse's CONTRIBUTING.md](https://github.com/CircuitVerse/CircuitVerse/blob/master/CONTRIBUTING.md)
> feat: introduce CONTRIBUTING.md

- analysis_options.yaml
- lib/main.dart
- lib/ui/views/about/about_tos_view.dart
- lib/ui/views/profile/edit_profile_view.dart
- pubspec.lock
- pubspec.yaml
Fixes #136 
1. Added all proper linter rules.
2. Migrated flutter-lints package.
This screenshot shows that "No issues found" i.e there is no warnings/errors in the code.
> feat: added flutter-lints package 

- analysis_options.yaml
- lib/models/ib/ib_content.dart
- lib/services/API/assignments_api.dart
- lib/services/API/collaborators_api.dart
- lib/services/API/contributors_api.dart
- lib/services/API/grades_api.dart
- lib/services/API/group_members_api.dart
- lib/services/API/groups_api.dart
- lib/services/API/projects_api.dart
- lib/services/API/users_api.dart
- lib/services/database_service.dart
- lib/services/ib_engine_service.dart
- lib/services/local_storage_service.dart
- lib/ui/components/cv_drawer_tile.dart
- lib/ui/components/cv_header.dart
- lib/ui/components/cv_html_editor.dart
- lib/ui/components/cv_outline_button.dart
- lib/ui/components/cv_primary_button.dart
- lib/ui/components/cv_text_field.dart
- lib/ui/components/cv_typeahead_field.dart
- lib/ui/views/about/about_privacy_policy_view.dart
- lib/ui/views/about/components/contributor_avatar.dart
- lib/ui/views/base_view.dart
- lib/ui/views/groups/components/group_card_button.dart
- lib/ui/views/ib/components/ib_pop_quiz_button.dart
- lib/ui/views/projects/components/featured_project_card.dart
- lib/utils/api_utils.dart
- lib/utils/enum_values.dart
- lib/utils/string_utils.dart
Fixes #149 
Describe the changes you have made in this PR - 
Enable following linter rules-
- always_put_required_named_parameters_first
- join_return_with_assignment
> Enable  linter rules

- lib/ui/views/ib/ib_page_view.dart
Fixes #173 
Hidden FAB's are now inactive, i.e do not do anything when tapped.
> Fixes: Hidden FAB's in Interactive Book are active when hidden. #173

- lib/ui/views/ib/ib_page_view.dart
Fixes #175 
Have added isEnabled field to TOC list tile to make it tappable/not tappable according to its location, for eg: not tappable on Chapter Content page but tappable on Bottom modal sheet.
> Fixes: #175

- lib/models/ib/ib_showcase.dart
- lib/services/local_storage_service.dart
- lib/ui/views/ib/ib_landing_view.dart
- lib/ui/views/ib/ib_page_view.dart
- lib/utils/router.dart
- lib/viewmodels/ib/ib_landing_viewmodel.dart
- lib/viewmodels/ib/ib_page_viewmodel.dart
- pubspec.lock
- pubspec.yaml
- test/ui_tests/ib/ib_landing_view_test.dart
- test/ui_tests/ib/ib_page_view_test.dart
Fixes #105 
I have added the `ShowCaseView` package to showcase the button and toggles on the Interactive book and model for storing the state of the button pressed. 
https://user-images.githubusercontent.com/77198905/142761255-e301a710-a738-4a09-91ce-238a765f150e.mp4
> ShowCaseView on Interactive Book

- analysis_options.yaml
- lib/services/database_service.dart
- lib/ui/components/cv_password_field.dart
- lib/ui/views/groups/add_assignment_view.dart
- lib/ui/views/groups/assignment_details_view.dart
- lib/ui/views/groups/update_assignment_view.dart
- lib/ui/views/ib/builders/ib_webview_builder.dart
- lib/ui/views/projects/project_details_view.dart
- lib/utils/router.dart
- test/service_tests/assignments_api_test.dart
- test/service_tests/users_api_test.dart
- test/ui_tests/groups/update_assignment_view_test.dart
Ref #149.
Enabled linter:
1. unnecessary_parenthesis
2. avoid_redundant_argument_values
> fix(lints): multiple linter rules #149

- lib/ui/views/authentication/signup_view.dart
- test/ui_tests/authentication/signup_view_test.dart
Fixes #197 
Added password validator for length of password  in signup screen. Earlier it was not there.
> Fixes: #197 Added password validator for length of password in signup screen

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/org/circuitverse/mobile_app/MainActivity.kt
- test/ui_tests/about/about_view_test.dart
> Migrate to the Android embedding v2

- lib/models/projects.dart
- lib/ui/views/profile/user_favourites_view.dart
- lib/ui/views/profile/user_projects_view.dart
- lib/ui/views/projects/featured_projects_view.dart
- lib/ui/views/projects/project_details_view.dart
- lib/viewmodels/profile/profile_viewmodel.dart
- lib/viewmodels/profile/user_favourites_viewmodel.dart
- lib/viewmodels/profile/user_projects_viewmodel.dart
- lib/viewmodels/projects/featured_projects_viewmodel.dart
- lib/viewmodels/projects/project_details_viewmodel.dart
- test/ui_tests/profile/user_favourites_view_test.dart
- test/ui_tests/profile/user_projects_view_test.dart
- test/ui_tests/projects/featured_projects_view_test.dart
- test/viewmodel_tests/projects/project_details_viewmodel_test.dart
Fixes #70 
Describe the changes you have made in this PR - The changed of state of starred is not reflected after the screen is popped. For example, in featured circuits if user starred a project then move back and again returning to that project still shows the previous state i.e. unstarred and similar thing in profile favorites section, if user unstarred the project then it is not removed from there.
https://user-images.githubusercontent.com/77198905/152423214-1ed2838f-43ab-4dd2-a417-bce211d99105.mp4
> fix(favorites): updated starred state is not reflecting

- lib/models/projects.dart
Fixes #207 
Added null check in lib/modal/project.dart
> solved null exception

- analysis_options.yaml
- lib/models/user.dart
- lib/ui/views/ib/builders/ib_webview_builder.dart
- lib/ui/views/ib/ib_landing_view.dart
- lib/ui/views/profile/profile_view.dart
- lib/viewmodels/ib/ib_page_viewmodel.dart
- lib/viewmodels/profile/profile_viewmodel.dart
- pubspec.lock
- pubspec.yaml
- test/ui_tests/profile/profile_view_test.dart
- test/viewmodel_tests/profile/profile_viewmodel_test.dart
Fixes #206 
Removed "Subscribe to mail" data from others' profiles.
My Profile:
Others profile-
> Fixes: #206 : Removed "subscribed to mail" data from others profile

- .github/workflows/ci.yml
- lib/services/API/group_members_api.dart
- lib/ui/views/groups/group_details_view.dart
- lib/viewmodels/groups/group_details_viewmodel.dart
- test/service_tests/group_members_api_test.dart
- test/viewmodel_tests/groups/group_details_viewmodel_test.dart
> Add directly as mentor in Group

- android/build.gradle
- lib/ui/views/profile/profile_view.dart
Fixes #
Describe the changes you have made in this PR -  As assigned, I had to change the boolean (True/False) value to more understandable (Yes/No). I did the same.
I ran 
flutter format
flutter analyze
flutter test
and did not encountered any error.
> Convert boolean value in profile page to yes/no #263
