CircuitVerse/mobile-app

lib/ui/views/contributors/components/contributors_donate_card.dart, lib/ui/views/contributors/components/contributors_support_card.dart, lib/ui/views/contributors/contributors_view.dart, test/contributors_view_test.dart
- Add Contributors View & related tests.
=> Add Contributors View & related tests

lib/ui/views/teachers/components/teachers_card.dart, lib/ui/views/teachers/teachers_view.dart, test/teachers_view_test.dart
- Add Teachers View & related tests.
=> Add Teachers View & related tests

lib/constants.dart, lib/locator.dart, lib/mock_data/contributors_mock_data.dart, lib/models/cv_contributors.dart, lib/models/failure_model.dart, lib/services/API/contributors_api.dart, lib/ui/views/about/about_view.dart, lib/ui/views/about/components/contributor_avatar.dart, lib/utils/api_utils.dart, lib/utils/app_exceptions.dart, lib/utils/enum_values.dart, lib/utils/image_test_utils.dart, lib/viewmodels/about/about_viewmodel.dart, test/about_view_test.dart, test/mocks.dart
- Add API utilities.
- Add About ViewModel bindings.
- Add About View & related tests.
=> Add About View & related tests

lib/utils/router.dart
=> Replace CupertinoPageRoute with MaterialPageRoute in router

lib/ui/views/about/about_privacy_policy_view.dart, lib/ui/views/about/about_tos_view.dart, lib/ui/views/about/about_view.dart, lib/utils/router.dart, pubspec.yaml, test/ui_tests/about/about_privacy_policy_view_test.dart, test/ui_tests/about/about_view_test.dart
This Pull Request adds natively written Privacy Policy page from https://circuitverse.org/privacy.
Content and links from site are untouched.
Link to Privacy Policy from Terms of Service page now routes to its native Privacy Policy page.
=> About CV: Bringup Privacy Policy page.

test/model_tests/add_collaborator_response_test.dart, test/model_tests/add_group_members_response_test.dart, test/model_tests/assignments_test.dart, test/model_tests/collaborators_test.dart, test/model_tests/grade_test.dart, test/model_tests/group_members_test.dart, test/model_tests/groups_test.dart, test/model_tests/links_test.dart, test/model_tests/projects_test.dart, test/setup/test_data/mock_assignments.dart, test/setup/test_data/mock_collaborators.dart, test/setup/test_data/mock_grade.dart, test/setup/test_data/mock_group_members.dart, test/setup/test_data/mock_groups.dart, test/setup/test_data/mock_links.dart, test/setup/test_data/mock_projects.dart
This Pull Request, adds model test for all the various models that needed proper unit testing.
=> Add Model Tests for several models

lib/ui/components/cv_password_field.dart, lib/ui/components/cv_text_field.dart, lib/ui/views/authentication/forgot_password_view.dart, lib/ui/views/authentication/login_view.dart, lib/ui/views/authentication/signup_view.dart
=> Added focus nodes

lib/locator.dart, lib/models/projects.dart, lib/services/API/projects_api.dart, lib/services/local_storage_service.dart, lib/ui/views/cv_landing_view.dart, lib/ui/views/home/home_view.dart, lib/ui/views/profile/profile_view.dart, lib/ui/views/projects/components/featured_project_card.dart, lib/ui/views/projects/featured_projects_view.dart, lib/ui/views/projects/project_details_view.dart, lib/utils/image_test_utils.dart, lib/utils/router.dart, lib/viewmodels/projects/featured_projects_viewmodel.dart, test/setup/test_helpers.dart, test/ui_tests/home/home_view_test.dart, test/ui_tests/projects/featured_projects_view_test.dart, test/viewmodel_tests/projects/featured_projects_viewmodel_test.dart
With the attempt to increase discovery of Circuits #30, this Pull Request adds Featured Circuits View and also shows top 3 featured circuits in Home View.
1. Adds Featured Circuits View
2. Adds Explore (Expandable Tile) > Featured Circuits in App Drawer.
3. Adds Editor Picks in Home which shows top 3 featured circuits.
Preview -
Screenshots -
=> Bringup Featured Circuits

lib/ui/views/profile/profile_view.dart, lib/ui/views/projects/components/project_card.dart, test/setup/test_helpers.dart, test/ui_tests/groups/my_groups_view_test.dart, test/ui_tests/profile/edit_profile_view_test.dart, test/ui_tests/profile/profile_view_test.dart, test/ui_tests/profile/user_favourites_view_test.dart, test/ui_tests/profile/user_projects_view_test.dart
This Pull Request adds UI Tests for Profile Views -
=> Add UI Tests for Profile Views

lib/ui/views/groups/add_assignment_view.dart, lib/ui/views/groups/assignment_details_view.dart, lib/ui/views/groups/update_assignment_view.dart, test/setup/test_helpers.dart, test/ui_tests/groups/add_assignment_view_test.dart, test/ui_tests/groups/assignment_details_view_test.dart, test/ui_tests/groups/edit_group_view_test.dart, test/ui_tests/groups/group_details_view_test.dart, test/ui_tests/groups/new_group_view_test.dart, test/ui_tests/groups/update_assignment_view_test.dart, test/ui_tests/profile/edit_profile_view_test.dart, test/ui_tests/profile/profile_view_test.dart, test/ui_tests/profile/user_favourites_view_test.dart, test/ui_tests/profile/user_projects_view_test.dart
In this Pull Request I have written all the required UI Tests for Groups View -
=> Add UI Tests for Groups.

lib/ui/views/projects/project_details_view.dart, pubspec.yaml
Fixes #59 
Added a share button in App bar of Project screen. 
=> Added share link button to project screen

lib/ui/views/groups/group_details_view.dart, lib/ui/views/projects/project_details_view.dart
The dialog is centered when the keyboard is not opened but adds itself a bottom padding exactly equal to the height of keyboard(default behaviour).
Fixes #72 
Removed the SIngleChildScrollView widget
Preview:
=> Add Member Dialog box alignment centered

.github/workflows/flutter-ci.yml
=> Temporarily allow fastlane branch to run.

.github/workflows/cd.yml, pubspec.yaml
- This PR is to test the deployment using fastlane github action.
=> Deploy 1.0.0+4

lib/ui/views/home/home_view.dart
Fixes #86 
Typo fixed in home_view.dart
=> fix: Timing spelling typo corrected

android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties
=> Gradle Upgrade

lib/ui/views/ib/builders/ib_interaction_builder.dart, lib/viewmodels/ib/ib_page_viewmodel.dart, test/viewmodel_tests/ib/ib_page_viewmodel_test.dart
Note: Please do not squash and merge.
=> fix(ib): builders deadlock between setState and FutureBuilder

lib/ui/views/ib/builders/ib_mathjax_builder.dart, lib/ui/views/ib/ib_page_view.dart, lib/ui/views/ib/syntaxes/ib_mathjax_syntax.dart, pubspec.lock, pubspec.yaml, test/ui_tests/ib/ib_page_view_test.dart
Feature(s):
Bug(s):
Note: Please don't squash and merge
=> feat(ib): beta Mathjax support

lib/models/ib/ib_content.dart, lib/services/ib_engine_service.dart, lib/ui/views/ib/builders/ib_headings_builder.dart, lib/ui/views/ib/ib_page_view.dart, pubspec.lock, pubspec.yaml, test/service_tests/ib_engine_test.dart
Ref #104
- Added package `scroll_to_index`
- Added custom headings builder having auto scroll tags by index
- Added action onTap headings in Table of Contents to scroll to the specific action
https://user-images.githubusercontent.com/22657113/128311138-56b4af10-bf50-4d3a-a7d0-ad3fc0d6491e.mp4
=> feat(ib): scroll to index links in table of contents

lib/ui/views/ib/builders/ib_headings_builder.dart, lib/ui/views/ib/syntaxes/ib_md_tag_syntax.dart
Added vertical paddings to Headings (h1-h6)
=> fix(ib): introduce vertical padding in headings

pubspec.yaml
* **119:** swap flutter_icons with fluttericon ([#129](https://github.com/CircuitVerse/mobile-app/issues/129)) ([f43c8c7](https://github.com/CircuitVerse/mobile-app/commit/f43c8c7d674d7e934a6ec9239791ca81395953ce))
* Added the on tap to disappear keyboard ([#55](https://github.com/CircuitVerse/mobile-app/issues/55)) ([df5c7dc](https://github.com/CircuitVerse/mobile-app/commit/df5c7dc9aa60d9c74863cbb54ae615ba7ab955a4))
* **i18n:** remove old i18n configuration and add new workflow for intl ([#124](https://github.com/CircuitVerse/mobile-app/issues/124)) ([0bce311](https://github.com/CircuitVerse/mobile-app/commit/0bce311ce5a10cb7994e60e0979247cd39a98254))
* **ib:** Add SVG Support to images. ([#114](https://github.com/CircuitVerse/mobile-app/issues/114)) …
=> build(mobile-app): bump to v1.1.0+5

CODE_OF_CONDUCT.md
Ref #139 
This Pull Request introduces Code of Conduct from CV's [Code of Conduct](https://github.com/CircuitVerse/CircuitVerse/blob/master/code-of-conduct.md).
=> feat: Introduce Code of Conduct

ios/Flutter/AppFrameworkInfo.plist, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, pubspec.lock
Ref: #135 
I followed this [answer](https://stackoverflow.com/a/64474526) and the build was successful.
=> fix iOS build failure

lib/ui/views/projects/project_details_view.dart, lib/ui/views/projects/project_preview_fullscreen_view.dart, lib/utils/router.dart
Fixes #83
Added button to view the circuit image in project details view in fullscreen.
Project Details        |  Project Preview
:-------------------------:|:-------------------------:
=> feat : Added button to view circuit image in fullscreen

pubspec.yaml
=> config: bump to 1.2.0+6 for production release

lib/services/database_service.dart, lib/ui/components/cv_password_field.dart, lib/ui/views/groups/assignment_details_view.dart, lib/ui/views/ib/builders/ib_webview_builder.dart, lib/ui/views/projects/project_details_view.dart, lib/utils/router.dart, pubspec.lock, pubspec.yaml, test/ui_tests/groups/update_assignment_view_test.dart
Fixes #
The app is actually not building in Flutter 2.8 . I have upgraded the version of some packages and the app is now working fine in android.
=> Flutter 2.8

lib/ui/components/cv_password_field.dart
Fixes #184 
Describe the changes you have made in this PR - Corrected behavior of Eye Icon
Screenshots of the changes (If any) - 
=> eye icon changed

android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties
fixes #189 
Describe the changes you have made in this PR - Upgraded gradle files to latest stable version to provide new schemas and avoid warnings
=> Mapping error resolved

pubspec.lock, pubspec.yaml
Fixes #
Describe the changes you have made in this PR - I have overridden the package `photo_view` because of the above-mentioned exception thrown by this package. 
Stacktrace:-
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous …
```
=> fix(photo_view): Looking up a deactivated widget's ancestor is unsafe

lib/services/API/country_institute_api.dart, test/setup/test_data/mock_country_data.dart
Fixes #212 
Updated URL of CountryInstituteAPI which is not loading earlier.
=> Fixes #212 Updated url of CountryInstituteAPI 

lib/ui/views/ib/builders/ib_headings_builder.dart, lib/ui/views/ib/builders/ib_highlight_builder.dart, lib/ui/views/ib/ib_landing_view.dart, lib/ui/views/ib/ib_page_view.dart, lib/ui/views/ib/syntaxes/ib_highlight_syntax.dart, lib/viewmodels/ib/ib_landing_viewmodel.dart, pubspec.lock, pubspec.yaml, test/ui_tests/ib/ib_landing_view_test.dart, test/ui_tests/ib/ib_page_view_test.dart
=> feat: search on the interactive book page

.github/workflows/cd.yml, pubspec.yaml
=> conf: bump build number

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, pubspec.yaml
=> conf: bump target sdk version

android/app/src/main/AndroidManifest.xml
Fixes #211
Fixed splash screen warning
=> Fixed deprecated splash screen #211

.metadata, android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/res/drawable-v21/launch_background.xml, android/app/src/main/res/values-night/styles.xml, lib/l10n/app_en.arb, lib/l10n/app_hi.arb, lib/locator.dart, lib/ui/components/cv_drawer.dart, lib/ui/views/simulator/simulator_view.dart, lib/utils/router.dart, lib/viewmodels/profile/profile_viewmodel.dart, lib/viewmodels/simulator/simulator_viewmodel.dart, pubspec.lock, pubspec.yaml
=> Embed simulator in the app

.github/workflows/ci.yml, lib/enums/notification_type.dart, lib/l10n/app_en.arb, lib/l10n/app_hi.arb, lib/locator.dart, lib/models/notification.dart, lib/models/user.dart, lib/services/notifications_service.dart, lib/ui/components/cv_drawer.dart, lib/ui/components/cv_drawer_tile.dart, lib/ui/components/cv_primary_button.dart, lib/ui/views/cv_landing_view.dart, lib/ui/views/groups/assignment_details_view.dart, lib/ui/views/groups/components/group_card_button.dart, lib/ui/views/groups/group_details_view.dart, lib/ui/views/notifications/notifications_view.dart, lib/ui/views/profile/profile_view.dart, lib/viewmodels/cv_landing_viewmodel.dart, lib/viewmodels/notifications/notifications_viewmodel.dart, pubspec.lock
=> feat(notification): implement notification in the mobile app

lib/ui/components/cv_flat_button.dart, pubspec.lock
Fixes #233 
There was a bug in **package:mobile_app/ui/components/cv_flat_button.dart** .
The **foregroundColor** was set to grey by default.  That's why the color of the button was not changing on state change.
https://user-images.githubusercontent.com/78409764/188433775-eb043b0b-a228-4ce7-b971-16cc1dc84d3c.mp4
=> fix: cvflatbutton active color does not change in dialog

.github/workflows/cd.yml, .github/workflows/ci.yml
Fixes #
I have bumped the version of `flutter-actions` in the actions. In the later version, they have resolved the architecture thing due to which the current CI is failing.
=> chor: bump action version

android/build.gradle, ios/Flutter/AppFrameworkInfo.plist, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, lib/ui/views/groups/assignment_details_view.dart, lib/ui/views/ib/builders/ib_webview_builder.dart, lib/ui/views/ib/ib_landing_view.dart, lib/ui/views/ib/ib_page_view.dart, lib/ui/views/projects/project_details_view.dart, pubspec.lock, pubspec.yaml, test/setup/test_helpers.dart, test/utils_tests/image_test_utils.dart
=> chor: bump dependencies

lib/ui/views/groups/group_details_view.dart, pubspec.lock, pubspec.yaml
Fixes #241 
Describe the changes you have made in this PR --
[create_chips.webm](https://user-images.githubusercontent.com/55531939/201894445-64241ec6-918b-4c8c-8457-2b8bf2123330.webm)
=> automatically create chips for email input

.github/workflows/ci.yml
=> Use v4 of upload artifacts
